package es.unizar.iaaa.crawler.butler.validator;

import es.unizar.iaaa.crawler.butler.model.CrawlConfiguration;

public interface Validator {

    ValidationResult validate(CrawlConfiguration config);

    public enum ErroresValidar {
        OK, ERROR_UNSUPPORTED_OS_VERSION, ERROR_UNSUPPORTED_OS_NAME,
        ERROR_UNSUPPORTED_CRAWL_VERSION, ERROR_UNSUPPORTED_CRAWL_NAME, ERROR_UNSUPPORTED_CRAWL_ROUNDS,
        ERROR_UNSUPPORTED_CRAWL_SEEDS, ERROR_UNSUPPORTED_CRAWL_PLUGINS, ERROR_UNSUPPORTED_CRAWL_INFO,
        ERROR_UNSUPPORTED_CRAWL_TIMEOUTS, ERROR_UNSUPPORTED_CRAWL_QUEUEMODE,
        ERROR_UNSUPPORTED_CRAWL_FILE_LENGTH, ERROR_UNSUPPORTED_CRAWL_LIMIT_URL, ERROR_UNSUPPORTED_CRAWL_DELAY
    }

}
